# Use an official Python runtime as a base image
FROM python:3.10-slim AS base

# Set the working directory inside the container
WORKDIR /app

# Install dependencies in a separate layer for better caching
FROM base AS dependencies

# Copy the requirements.txt 
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code into the container
FROM base AS final

WORKDIR /app

# Copy the installed dependencies from the previous stage
COPY --from=dependencies /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages

# Copy application code into the container
COPY . .

# Expose the port 
EXPOSE 5000

# Command to run the application using uvicorn
CMD ["uvicorn", "API_Version2:app", "--host", "0.0.0.0", "--port", "5000"]
